import sys
import os

# Add backend directory to sys.path
backend_dir = os.path.abspath("backend")
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

print("--- 1. Testing Health Endpoint ---")
res = client.get("/api/health")
assert res.status_code == 200, f"Health check failed: {res.text}"
print("Health Status:", res.json())

print("\n--- 2. Testing Cities Endpoint ---")
res = client.get("/api/cities")
assert res.status_code == 200
cities = res.json()
print("Available Cities Count:", len(cities))
assert "Bengaluru" in cities

print("\n--- 3. Testing Symptom Analysis (Tri-Paradigm) ---")
payload = {
    "symptoms": "Severe burning sensation in chest, acid reflux, stomach bloating for 2 weeks after dinner",
    "age": 34,
    "gender": "Female",
    "duration": "1-2 weeks",
    "severity": "Moderate",
    "city": "Bengaluru"
}
res = client.post("/api/analyze", json=payload)
assert res.status_code == 200, f"Analyze failed: {res.text}"
analysis = res.json()
print("Symptom Summary:", analysis["symptom_summary"])
print("Generated By:", analysis["generated_by"])

# Verify Ayurveda
assert "ayurveda" in analysis
assert len(analysis["ayurveda"]["herbal_remedies"]) > 0
print("Ayurveda Dosha:", analysis["ayurveda"]["dosha_imbalance"])
print("Ayurveda 1st Herb:", analysis["ayurveda"]["herbal_remedies"][0]["name"])

# Verify Homeopathy
assert "homeopathy" in analysis
assert len(analysis["homeopathy"]["remedies"]) > 0
print("Homeopathy Miasm:", analysis["homeopathy"]["constitutional_type"])
print("Homeopathy 1st Remedy:", analysis["homeopathy"]["remedies"][0]["name"])

# Verify Allopathy
assert "allopathy" in analysis
assert len(analysis["allopathy"]["diagnostic_tests"]) > 0
assert len(analysis["allopathy"]["conventional_medications"]) > 0
print("Allopathy Diagnosis:", analysis["allopathy"]["probable_diagnosis"])
print("Allopathy Red Flags Count:", len(analysis["allopathy"]["red_flags"]))

# Verify Comparison
assert "comparison" in analysis
print("Comparison Relief Speed:", analysis["comparison"]["speed_of_relief"])

print("\n--- 4. Testing Doctor Recommendations ---")
# Filter Bengaluru + Ayurveda
res = client.get("/api/doctors?city=Bengaluru&system=Ayurveda")
assert res.status_code == 200
ayur_docs = res.json()
print(f"Found {len(ayur_docs)} Ayurvedic doctors in Bengaluru")
assert len(ayur_docs) > 0
first_doc = ayur_docs[0]
print(f"First Doctor: {first_doc['name']} ({first_doc['degrees']}) - {first_doc['specialty']}")

print("\n--- 5. Testing Available Slots ---")
doc_id = first_doc["id"]
test_date = "2026-09-15"
res = client.get(f"/api/doctors/{doc_id}/slots?date={test_date}")
assert res.status_code == 200
slots_data = res.json()
print(f"Total Slots: {len(slots_data['all_slots'])}, Available: {len(slots_data['available_slots'])}")
assert len(slots_data["available_slots"]) > 0
slot_to_book = slots_data["available_slots"][0]

print(f"\n--- 6. Testing Slot Booking for slot {slot_to_book} ---")
booking_payload = {
    "doctor_id": doc_id,
    "doctor_name": first_doc["name"],
    "doctor_system": first_doc["system"],
    "doctor_specialty": first_doc["specialty"],
    "clinic_name": first_doc["clinic_name"],
    "clinic_address": first_doc["address"],
    "patient_name": "Aditi Sharma",
    "patient_phone": "+91 98765 01234",
    "patient_email": "aditi.sharma@example.com",
    "patient_age": 34,
    "appointment_date": test_date,
    "appointment_time": slot_to_book,
    "consultation_mode": "In-Clinic",
    "symptoms": "Acid reflux and chest burning",
    "consultation_fee": first_doc["consultation_fee"]
}
res = client.post("/api/appointments", json=booking_payload)
assert res.status_code == 200, f"Booking failed: {res.text}"
booked_apt = res.json()
print("Booked Successfully! Ref:", booked_apt["booking_ref"])
print("Status:", booked_apt["status"])
print("QR Payload:", booked_apt["qr_code_data"])

print("\n--- 7. Testing Double Booking Conflict Prevention ---")
res_dup = client.post("/api/appointments", json=booking_payload)
assert res_dup.status_code == 409, f"Expected 409 Conflict for double booking, got: {res_dup.status_code}"
print("Double booking correctly rejected with status 409 Conflict!")

print("\n--- 8. Testing Appointment Listing ---")
res_list = client.get("/api/appointments")
assert res_list.status_code == 200
all_apts = res_list.json()
assert any(a["id"] == booked_apt["id"] for a in all_apts)
print(f"Total active/past appointments in DB: {len(all_apts)}")

print("\n--- 9. Testing Appointment Cancellation ---")
res_cancel = client.delete(f"/api/appointments/{booked_apt['id']}")
assert res_cancel.status_code == 200
print(f"Appointment {booked_apt['booking_ref']} cancelled successfully!")

print("\n========================================================")
print("  ALL 9 INTEGRATION & CLINICAL TESTS PASSED PERFECTLY!  ")
print("========================================================")
