from typing import List, Dict, Any

CITIES = [
    # Bihar
    "Patna",
    "Gaya",
    "Muzaffarpur",
    "Bhagalpur",
    "Darbhanga",
    # Uttar Pradesh (UP)
    "Lucknow",
    "Varanasi",
    "Kanpur",
    "Prayagraj",
    "Agra",
    "Gorakhpur",
    "Noida",
    # Other Major Hubs
    "Bengaluru",
    "Mumbai",
    "Delhi NCR",
    "Hyderabad",
    "Pune",
    "Chennai",
    "Kolkata",
    "Jaipur",
    "Ahmedabad",
    "Chandigarh",
]

DOCTORS_DATABASE: List[Dict[str, Any]] = [
    # ------------------ BENGALURU ------------------
    # Ayurveda
    {
        "id": "doc-blr-ayu-1",
        "name": "Dr. Aarav Nambiar",
        "system": "Ayurveda",
        "specialty": "Panchakarma & Digestive Health",
        "degrees": "BAMS, MD (Ayurveda), Gold Medalist",
        "experience_years": 16,
        "rating": 4.9,
        "review_count": 342,
        "clinic_name": "Kottakkal Arya Vaidya Sala Center",
        "address": "12th Main, HAL 2nd Stage, Indiranagar, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 1.4,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Specialized in chronic gut health, Pitta dosha balancing, and clinical Panchakarma detox.",
        "slots": ["09:30 AM", "11:00 AM", "02:30 PM", "04:30 PM", "06:00 PM"],
        "phone": "+91 80 2520 1199"
    },
    {
        "id": "doc-blr-ayu-2",
        "name": "Dr. Sunidhi Kulkarni",
        "system": "Ayurveda",
        "specialty": "Joint Disorders, Spine & Vata Shaman",
        "degrees": "BAMS, MS (Shalya Tantra)",
        "experience_years": 12,
        "rating": 4.8,
        "review_count": 218,
        "clinic_name": "AyurVAID Hospital",
        "address": "24, 7th Block, Koramangala, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 2.8,
        "consultation_fee": 800,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Renowned for treating cervical spondylosis, osteoarthritis, and sciatic nerve discomfort naturally.",
        "slots": ["10:00 AM", "11:30 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 80 4110 8822"
    },
    {
        "id": "doc-blr-ayu-3",
        "name": "Dr. Radheshyam Sharma",
        "system": "Ayurveda",
        "specialty": "Stress, Migraine & Insomnia (Manovaha Srotas)",
        "degrees": "BAMS, Ph.D (Kayachikitsa, NIA Jaipur)",
        "experience_years": 22,
        "rating": 4.9,
        "review_count": 480,
        "clinic_name": "Sri Sri Tattva Panchakarma Clinic",
        "address": "45, Outer Ring Road, Bellandur, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 3.9,
        "consultation_fee": 900,
        "available_today": False,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Master practitioner of Shirodhara and classical herbal rasayanas for neurological calming.",
        "slots": ["09:00 AM", "10:30 AM", "01:30 PM", "04:00 PM"],
        "phone": "+91 80 6701 4455"
    },
    # Homeopathy
    {
        "id": "doc-blr-hom-1",
        "name": "Dr. Malcolm Fernandez",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Chronic Allergies",
        "degrees": "BHMS, MD (Homeo), London Fellowship",
        "experience_years": 18,
        "rating": 4.8,
        "review_count": 290,
        "clinic_name": "Dr. Fernandez Classical Care",
        "address": "88, Lavelle Road, Shanthala Nagar, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 2.1,
        "consultation_fee": 750,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "In-depth constitutional totality analysis for persistent sinusitis, asthma, and skin eczema.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "05:00 PM", "07:00 PM"],
        "phone": "+91 80 2221 4433"
    },
    {
        "id": "doc-blr-hom-2",
        "name": "Dr. Prerna Deshmukh",
        "system": "Homeopathy",
        "specialty": "Pediatric & Hormonal/Metabolic Care",
        "degrees": "BHMS, MD (Repertory)",
        "experience_years": 14,
        "rating": 4.9,
        "review_count": 315,
        "clinic_name": "Similia Homeo Healing",
        "address": "15, 17th Cross, HSR Layout Sector 4, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 3.2,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 93,
        "match_reason": "High success in gentle root treatment of PCOD, recurring childhood coughs, and migraines.",
        "slots": ["09:30 AM", "11:00 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 80 2572 6677"
    },
    # Allopathy
    {
        "id": "doc-blr-all-1",
        "name": "Dr. Vikramaditya Reddy",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD (Gen Med), DM (Gastro, AIIMS)",
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 520,
        "clinic_name": "Manipal Hospital Gastro Center",
        "address": "98, HAL Old Airport Rd, Kodihalli, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 1.9,
        "consultation_fee": 1100,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Expert evidence-based management of GERD, IBS, peptic ulcers, and liver biochemistry.",
        "slots": ["09:00 AM", "10:00 AM", "11:30 AM", "03:00 PM", "04:30 PM"],
        "phone": "+91 80 2502 4444"
    },
    {
        "id": "doc-blr-all-2",
        "name": "Dr. Ananya Singhania",
        "system": "Allopathy",
        "specialty": "Neurology & Headache Specialist",
        "degrees": "MBBS, MD (Medicine), DM (Neurology, NIMHANS)",
        "experience_years": 15,
        "rating": 4.8,
        "review_count": 390,
        "clinic_name": "Aster CMI Hospital",
        "address": "No. 43/42, NH 44, Hebbal, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 4.5,
        "consultation_fee": 1200,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Leading neurologist specializing in intractable migraine, cluster headaches, and neuropathy.",
        "slots": ["10:30 AM", "12:00 PM", "02:30 PM", "05:00 PM"],
        "phone": "+91 80 4342 0100"
    },
    {
        "id": "doc-blr-all-3",
        "name": "Dr. Rohan Mathew",
        "system": "Allopathy",
        "specialty": "Orthopedics & Rheumatology",
        "degrees": "MBBS, MS (Ortho), Fellowship in Joint Replacement",
        "experience_years": 17,
        "rating": 4.9,
        "review_count": 440,
        "clinic_name": "Fortis Hospital Ortho Suite",
        "address": "154/9, Bannerghatta Main Rd, Opposite IIMB, Bengaluru",
        "city": "Bengaluru",
        "distance_km": 3.8,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "High precision diagnostic workup for inflammatory arthritis, meniscus tears, and spinal stenosis.",
        "slots": ["09:00 AM", "11:00 AM", "03:30 PM", "06:00 PM"],
        "phone": "+91 80 6621 4444"
    },

    # ------------------ MUMBAI ------------------
    # Ayurveda
    {
        "id": "doc-mum-ayu-1",
        "name": "Vaidya Shrirang Joshi",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Kayachikitsa & Metabolic Care",
        "degrees": "BAMS, MD (Ayu, Podar Medical College)",
        "experience_years": 25,
        "rating": 4.9,
        "review_count": 610,
        "clinic_name": "Shree Vishwa Ayurveda Sansthan",
        "address": "Shivaji Park, Dadar West, Mumbai",
        "city": "Mumbai",
        "distance_km": 2.2,
        "consultation_fee": 850,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Senior Vaidya recognized for Nadi Pariksha (pulse diagnosis) and metabolic toxin removal (Ama).",
        "slots": ["10:00 AM", "11:30 AM", "04:00 PM", "06:30 PM"],
        "phone": "+91 22 2445 6789"
    },
    {
        "id": "doc-mum-ayu-2",
        "name": "Dr. Gayatri Patwardhan",
        "system": "Ayurveda",
        "specialty": "Skin Diseases & Chronic Allergies (Twak Roga)",
        "degrees": "BAMS, MD (Rasashastra)",
        "experience_years": 15,
        "rating": 4.8,
        "review_count": 320,
        "clinic_name": "AyurCare Skin & Holistic Clinic",
        "address": "Linking Road, Bandra West, Mumbai",
        "city": "Mumbai",
        "distance_km": 1.7,
        "consultation_fee": 900,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Herbal blood purifiers and customized Lepam applications for psoriasis and allergic hives.",
        "slots": ["11:00 AM", "01:00 PM", "03:30 PM", "05:30 PM"],
        "phone": "+91 22 2640 1122"
    },
    # Homeopathy
    {
        "id": "doc-mum-hom-1",
        "name": "Dr. Jamshed Batliwala",
        "system": "Homeopathy",
        "specialty": "Classical Constitutional & Mind-Body Health",
        "degrees": "LCEH, MD (Homeo), Gold Medalist",
        "experience_years": 28,
        "rating": 5.0,
        "review_count": 780,
        "clinic_name": "Batliwala Homeo Clinic",
        "address": "Cumballa Hill, Kemps Corner, Mumbai",
        "city": "Mumbai",
        "distance_km": 3.1,
        "consultation_fee": 1200,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Renowned across South Mumbai for treating psychosomatic migraines, vertigo, and anxiety.",
        "slots": ["09:00 AM", "11:00 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 22 2387 9900"
    },
    {
        "id": "doc-mum-hom-2",
        "name": "Dr. Tanvi Merchant",
        "system": "Homeopathy",
        "specialty": "Digestive Complaints & Respiratory Allergies",
        "degrees": "BHMS, MSc (Clinical Research)",
        "experience_years": 11,
        "rating": 4.8,
        "review_count": 210,
        "clinic_name": "Cura Homeopathy Studio",
        "address": "Near Juhu Circle, Andheri West, Mumbai",
        "city": "Mumbai",
        "distance_km": 2.5,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Gentle, non-habit-forming homeopathic regimens for chronic hyperacidity and irritable bowel.",
        "slots": ["10:30 AM", "01:30 PM", "04:00 PM", "06:00 PM"],
        "phone": "+91 22 2673 8811"
    },
    # Allopathy
    {
        "id": "doc-mum-all-1",
        "name": "Dr. Cyrus Contractor",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Hepatology",
        "degrees": "MBBS, MD (Med), DM (Gastro), FRCP (London)",
        "experience_years": 24,
        "rating": 4.9,
        "review_count": 640,
        "clinic_name": "Lilavati Hospital & Research Centre",
        "address": "A-791, Bandra Reclamation, Bandra West, Mumbai",
        "city": "Mumbai",
        "distance_km": 1.5,
        "consultation_fee": 1500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Top gastroenterologist with state-of-the-art endoscopy and acid reflux diagnosis.",
        "slots": ["11:00 AM", "12:30 PM", "03:00 PM", "05:00 PM"],
        "phone": "+91 22 2675 1000"
    },
    {
        "id": "doc-mum-all-2",
        "name": "Dr. Neha Parekh",
        "system": "Allopathy",
        "specialty": "Dermatology & Cosmetology",
        "degrees": "MBBS, MD (Dermatology, KEM Hospital)",
        "experience_years": 13,
        "rating": 4.8,
        "review_count": 380,
        "clinic_name": "Kokilaben Dhirubhai Ambani Hospital",
        "address": "Rao Saheb Achutrao Patwardhan Marg, Andheri West, Mumbai",
        "city": "Mumbai",
        "distance_km": 3.4,
        "consultation_fee": 1200,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Evidence-based targeted therapy for contact dermatitis, severe cystic acne, and eczema flare-ups.",
        "slots": ["09:30 AM", "11:30 AM", "02:30 PM", "04:30 PM"],
        "phone": "+91 22 4269 6969"
    },

    # ------------------ DELHI NCR ------------------
    # Ayurveda
    {
        "id": "doc-del-ayu-1",
        "name": "Acharya Dr. Devendra Shastri",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Internal Medicine & Nadi Pariksha",
        "degrees": "BAMS, MD (Ayu), All India Institute of Ayurveda",
        "experience_years": 21,
        "rating": 4.9,
        "review_count": 550,
        "clinic_name": "Chikitshak Wellness Heritage",
        "address": "E-24, South Extension Part II, New Delhi",
        "city": "Delhi NCR",
        "distance_km": 2.0,
        "consultation_fee": 800,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Holistic Agni restoration, detoxification protocols, and authentic dosha diagnosis.",
        "slots": ["09:00 AM", "10:30 AM", "01:00 PM", "04:00 PM", "06:00 PM"],
        "phone": "+91 11 2625 3322"
    },
    {
        "id": "doc-del-ayu-2",
        "name": "Dr. Meenakshi Tiwari",
        "system": "Ayurveda",
        "specialty": "Respiratory Disorders & Immunity (Pranavaha Srotas)",
        "degrees": "BAMS, MD (Dravyaguna)",
        "experience_years": 14,
        "rating": 4.8,
        "review_count": 275,
        "clinic_name": "Patanjali Wellness Speciality Clinic",
        "address": "Sector 14, Gurugram, Delhi NCR",
        "city": "Delhi NCR",
        "distance_km": 3.7,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Expert in combatting North India's seasonal pollution cough, bronchitis, and allergic rhinitis.",
        "slots": ["10:00 AM", "12:00 PM", "03:00 PM", "05:00 PM"],
        "phone": "+91 124 405 9911"
    },
    # Homeopathy
    {
        "id": "doc-del-hom-1",
        "name": "Dr. Harpreet Singh Bakshi",
        "system": "Homeopathy",
        "specialty": "Chronic Immune & Skin Disorders",
        "degrees": "BHMS, MD (Homeo, Nehru Homeo College)",
        "experience_years": 23,
        "rating": 4.9,
        "review_count": 490,
        "clinic_name": "Bakshi Homoeopathic PolyClinic",
        "address": "A-12, Ring Road, Lajpat Nagar IV, New Delhi",
        "city": "Delhi NCR",
        "distance_km": 1.8,
        "consultation_fee": 850,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Decades of proven patient recoveries from urticaria, eczema, and dust allergies.",
        "slots": ["09:30 AM", "11:30 AM", "03:30 PM", "05:30 PM"],
        "phone": "+91 11 2984 4567"
    },
    # Allopathy
    {
        "id": "doc-del-all-1",
        "name": "Dr. Sanjeev Sachdeva",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Interventional Endoscopy",
        "degrees": "MBBS, MD, DM (Gastro, Maulana Azad)",
        "experience_years": 22,
        "rating": 5.0,
        "review_count": 680,
        "clinic_name": "Max Super Speciality Hospital",
        "address": "1, 2, Press Enclave Road, Saket, New Delhi",
        "city": "Delhi NCR",
        "distance_km": 2.5,
        "consultation_fee": 1400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Nationally acclaimed specialist in refractory acid peptic disorders and gastrointestinal motilities.",
        "slots": ["10:00 AM", "11:30 AM", "02:00 PM", "04:00 PM"],
        "phone": "+91 11 2651 5050"
    },
    {
        "id": "doc-del-all-2",
        "name": "Dr. Pallavi Chawla",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Preventive Health",
        "degrees": "MBBS, MD (Medicine, Safdarjung Hospital)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 340,
        "clinic_name": "Apollo Hospitals Apollo Cradle",
        "address": "Sector 14, Dwarka, New Delhi",
        "city": "Delhi NCR",
        "distance_km": 4.2,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Holistic allopathic management balancing lifestyle, pharmacotherapy, and diagnostic markers.",
        "slots": ["09:00 AM", "11:00 AM", "01:30 PM", "05:00 PM"],
        "phone": "+91 11 4056 7000"
    },

    # ------------------ HYDERABAD ------------------
    # Ayurveda
    {
        "id": "doc-hyd-ayu-1",
        "name": "Dr. K. S. Ramanujam",
        "system": "Ayurveda",
        "specialty": "Classical Panchakarma & Musculoskeletal Care",
        "degrees": "BAMS, MD (Ayu, Dr. BRKR Govt Ayu College)",
        "experience_years": 19,
        "rating": 4.9,
        "review_count": 310,
        "clinic_name": "Amrutha Ayurvedic Healing Centre",
        "address": "Road No. 36, Jubilee Hills, Hyderabad",
        "city": "Hyderabad",
        "distance_km": 2.0,
        "consultation_fee": 750,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Specialized in spinal Kati Basti therapies and metabolic Pitta balancing.",
        "slots": ["09:30 AM", "11:30 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 40 2355 8899"
    },
    # Homeopathy
    {
        "id": "doc-hyd-hom-1",
        "name": "Dr. V. Sudhakar Rao",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Autoimmune Care",
        "degrees": "BHMS, MD (Homeopathy, J.S.P.S. College)",
        "experience_years": 22,
        "rating": 4.8,
        "review_count": 420,
        "clinic_name": "Positive Homeopathy Banjara Hills",
        "address": "Road No. 12, Banjara Hills, Hyderabad",
        "city": "Hyderabad",
        "distance_km": 2.4,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "High reputation in individualized constitutional prescriptions for allergic asthma and arthritis.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 40 2339 1234"
    },
    # Allopathy
    {
        "id": "doc-hyd-all-1",
        "name": "Dr. Nageshwar Reddy",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Therapeutic Endoscopy",
        "degrees": "MBBS, MD, DM, DSc (Gastro)",
        "experience_years": 27,
        "rating": 5.0,
        "review_count": 890,
        "clinic_name": "AIG Hospitals (Asian Institute of Gastroenterology)",
        "address": "Mindspace Rd, Gachibowli, Hyderabad",
        "city": "Hyderabad",
        "distance_km": 3.5,
        "consultation_fee": 1500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Global authority in digestive diseases, acid reflux, peptic ulcers, and bowel disorders.",
        "slots": ["09:00 AM", "10:30 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 40 4244 4222"
    },

    # ------------------ PUNE ------------------
    # Ayurveda
    {
        "id": "doc-pune-ayu-1",
        "name": "Vaidya Suhas Ranade",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Pharmacology & Agni Treatment",
        "degrees": "BAMS, MD (Ayu, Tilak Ayurveda Mahavidyalaya)",
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 380,
        "clinic_name": "Tilak Ayurveda Research Clinic",
        "address": "Rasta Peth, Somwar Peth, Pune",
        "city": "Pune",
        "distance_km": 1.8,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Direct lineage of classical Maharashtrian Ayurveda, balancing tridoshas through custom herbal teas.",
        "slots": ["09:30 AM", "11:30 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 20 2612 3456"
    },
    # Homeopathy
    {
        "id": "doc-pune-hom-1",
        "name": "Dr. Aniket Sankpal",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Skin Allergies",
        "degrees": "BHMS, MD (Hom)",
        "experience_years": 15,
        "rating": 4.8,
        "review_count": 260,
        "clinic_name": "Sankpal Healing Homeo Clinic",
        "address": "FC Road, Deccan Gymkhana, Pune",
        "city": "Pune",
        "distance_km": 2.2,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Holistic therapy for persistent urticaria, allergic rhinitis, and migraine episodes.",
        "slots": ["10:00 AM", "12:30 PM", "04:00 PM", "06:30 PM"],
        "phone": "+91 20 2553 7890"
    },
    # Allopathy
    {
        "id": "doc-pune-all-1",
        "name": "Dr. Shailesh Putambekar",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD, DNB (Gastroenterology)",
        "experience_years": 18,
        "rating": 4.9,
        "review_count": 420,
        "clinic_name": "Ruby Hall Clinic Medical Center",
        "address": "40, Sassoon Rd, Sangamvadi, Pune",
        "city": "Pune",
        "distance_km": 2.1,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Comprehensive evidence-based diagnosis with high precision labs and ultrasound imaging.",
        "slots": ["09:00 AM", "11:00 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 20 6645 5100"
    },

    # ------------------ CHENNAI ------------------
    # Ayurveda
    {
        "id": "doc-chn-ayu-1",
        "name": "Dr. S. Parameswaran",
        "system": "Ayurveda",
        "specialty": "Authentic Kerala Ayurveda & Spine Care",
        "degrees": "BAMS, MD (Ayu, Kottakkal)",
        "experience_years": 23,
        "rating": 4.9,
        "review_count": 410,
        "clinic_name": "Arya Vaidya Pharmacy (AVP) Centre",
        "address": "Gandhi Nagar, Adyar, Chennai",
        "city": "Chennai",
        "distance_km": 1.9,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Specialist in classical Kizhi, Pizhichil, and Vata-pacifying medicated decoctions.",
        "slots": ["09:00 AM", "11:00 AM", "02:30 PM", "05:00 PM"],
        "phone": "+91 44 2441 2345"
    },
    # Homeopathy
    {
        "id": "doc-chn-hom-1",
        "name": "Dr. Karpagam Soundararajan",
        "system": "Homeopathy",
        "specialty": "Constitutional Healing & Chronic Sinusitis",
        "degrees": "BHMS, MD (Hom)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 290,
        "clinic_name": "Saraswathi Homeo Specialty Clinic",
        "address": "T. Nagar, Usman Road, Chennai",
        "city": "Chennai",
        "distance_km": 2.5,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Excellent outcomes in pediatric allergies, nasal polyps, and recurrent migraines.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 44 2815 6789"
    },
    # Allopathy
    {
        "id": "doc-chn-all-1",
        "name": "Dr. Mohan K. Subramanian",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD (General Med), DM (Gastro, Madras Medical)",
        "experience_years": 21,
        "rating": 4.9,
        "review_count": 590,
        "clinic_name": "Apollo Hospitals Greams Road",
        "address": "21 Greams Lane, Thousand Lights, Chennai",
        "city": "Chennai",
        "distance_km": 2.2,
        "consultation_fee": 1100,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "State of the art therapeutic endoscopy and clinical pharmacological interventions for GI distress.",
        "slots": ["09:30 AM", "11:30 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 44 2829 0200"
    },

    # ------------------ KOLKATA ------------------
    # Ayurveda
    {
        "id": "doc-kol-ayu-1",
        "name": "Kaviraj Dr. Subhashish Roy",
        "system": "Ayurveda",
        "specialty": "Classical Nadi Pariksha & Liver/Digestive Care",
        "degrees": "BAMS, MD (Ayu, JB Roy State Ayurvedic College)",
        "experience_years": 24,
        "rating": 4.9,
        "review_count": 430,
        "clinic_name": "Bengal Ayurvedic Health Foundation",
        "address": "170, Raja Dinendra Street, Shyambazar, Kolkata",
        "city": "Kolkata",
        "distance_km": 1.6,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Deep heritage in Bengal Ayurvedic rasayanas for liver sluggishness and chronic indigestion.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 33 2555 4321"
    },
    # Homeopathy
    {
        "id": "doc-kol-hom-1",
        "name": "Dr. Bhaswati Mukhopadhyay",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Mind-Body Health",
        "degrees": "BHMS, MD (Hom, National Institute of Homeopathy)",
        "experience_years": 20,
        "rating": 5.0,
        "review_count": 670,
        "clinic_name": "Hahnemannian Cure Sanctuary",
        "address": "Salt Lake Sector 1, Kolkata",
        "city": "Kolkata",
        "distance_km": 2.8,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Alumnus of NIH Kolkata with unmatched expertise in constitutional single-remedy treatment.",
        "slots": ["10:00 AM", "12:00 PM", "02:30 PM", "04:30 PM"],
        "phone": "+91 33 2337 8899"
    },
    # Allopathy
    {
        "id": "doc-kol-all-1",
        "name": "Dr. Arindam Banerjee",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Internal Medicine",
        "degrees": "MBBS, MD, DM (Gastroenterology, IPGMER)",
        "experience_years": 19,
        "rating": 4.9,
        "review_count": 510,
        "clinic_name": "AMRI Hospitals Dhakuria",
        "address": "P-4&5, Gariahat Rd Block A, Scheme L11, Kolkata",
        "city": "Kolkata",
        "distance_km": 2.4,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Advanced diagnostic evaluation for GERD, Helicobacter pylori gastritis, and IBS symptoms.",
        "slots": ["09:30 AM", "11:30 AM", "01:30 PM", "04:00 PM"],
        "phone": "+91 33 6680 0000"
    },

    # ------------------ JAIPUR ------------------
    # Ayurveda
    {
        "id": "doc-jpr-ayu-1",
        "name": "Dr. Brijmohan Rathore",
        "system": "Ayurveda",
        "specialty": "National Institute of Ayurveda Senior Specialist",
        "degrees": "BAMS, MD (Ayu), Ph.D (Kayachikitsa)",
        "experience_years": 26,
        "rating": 5.0,
        "review_count": 720,
        "clinic_name": "Rathore AyurVeda Healing Center",
        "address": "Near Jorawar Singh Gate, Amer Road, Jaipur",
        "city": "Jaipur",
        "distance_km": 1.5,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Former Head at NIA Jaipur, master in herbal compound formulations and digestive rasayanas.",
        "slots": ["09:00 AM", "10:30 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 141 263 5544"
    },
    # Homeopathy
    {
        "id": "doc-jpr-hom-1",
        "name": "Dr. Narendra Soni",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Skin Treatment",
        "degrees": "BHMS, MD (Hom, Madan Pratap Khunteta)",
        "experience_years": 17,
        "rating": 4.8,
        "review_count": 280,
        "clinic_name": "Soni Homeopathic Clinic",
        "address": "MI Road, Panch Batti, Jaipur",
        "city": "Jaipur",
        "distance_km": 1.9,
        "consultation_fee": 550,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Holistic treatments for recurring boils, psoriasis, and tension headaches.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 141 236 7890"
    },
    # Allopathy
    {
        "id": "doc-jpr-all-1",
        "name": "Dr. Alok Khandelwal",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Hepatology",
        "degrees": "MBBS, MD, DM (Gastroenterology, SMS Hospital)",
        "experience_years": 16,
        "rating": 4.9,
        "review_count": 390,
        "clinic_name": "Fortis Escorts Hospital",
        "address": "Jawaharlal Nehru Marg, Malviya Nagar, Jaipur",
        "city": "Jaipur",
        "distance_km": 2.7,
        "consultation_fee": 900,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Modern pharmacological therapies and diagnostic upper GI endoscopic interventions.",
        "slots": ["09:30 AM", "11:30 AM", "01:30 PM", "04:00 PM"],
        "phone": "+91 141 254 7000"
    },

    # ------------------ AHMEDABAD ------------------
    # Ayurveda
    {
        "id": "doc-ahd-ayu-1",
        "name": "Dr. Hemant Raval",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Gastroenterology & Panchakarma",
        "degrees": "BAMS, MD (Ayu, Gujarat Ayurved University)",
        "experience_years": 18,
        "rating": 4.9,
        "review_count": 360,
        "clinic_name": "Shri Dhanvantari Ayurveda Clinic",
        "address": "CG Road, Navrangpura, Ahmedabad",
        "city": "Ahmedabad",
        "distance_km": 1.7,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Jamnagar university trained expert in digestive Agni and Pitta detoxification.",
        "slots": ["09:30 AM", "11:00 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 79 2640 1234"
    },
    # Homeopathy
    {
        "id": "doc-ahd-hom-1",
        "name": "Dr. Kruti Bhatt",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Allergy Relief",
        "degrees": "BHMS, MD (Hom)",
        "experience_years": 13,
        "rating": 4.8,
        "review_count": 240,
        "clinic_name": "PureLife Homeo Clinic",
        "address": "Satellite Road, Near Star Bazaar, Ahmedabad",
        "city": "Ahmedabad",
        "distance_km": 2.3,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 93,
        "match_reason": "Gentle micro-dilution remedies for allergic bronchospasm and migraine relief.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 79 2692 5678"
    },
    # Allopathy
    {
        "id": "doc-ahd-all-1",
        "name": "Dr. Pratik Vora",
        "system": "Allopathy",
        "specialty": "Gastroenterology & GI Endoscopy",
        "degrees": "MBBS, MD, DM (Gastroenterology, BJ Medical)",
        "experience_years": 17,
        "rating": 4.9,
        "review_count": 460,
        "clinic_name": "Zydus Hospitals Medical Suite",
        "address": "Zydus Hospital Road, Thaltej, Ahmedabad",
        "city": "Ahmedabad",
        "distance_km": 3.0,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Expert clinical protocol for chronic GERD, peptic ulcers, and functional dyspepsia.",
        "slots": ["09:00 AM", "11:00 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 79 6619 0201"
    },

    # ------------------ CHANDIGARH ------------------
    # Ayurveda
    {
        "id": "doc-chd-ayu-1",
        "name": "Dr. Gurpreet Singh Sandhu",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Kayachikitsa & Joint Care",
        "degrees": "BAMS, MD (Ayu), Dabur Certified Vaidya",
        "experience_years": 17,
        "rating": 4.9,
        "review_count": 310,
        "clinic_name": "Chandigarh Ayurveda & Panchakarma Center",
        "address": "SCO 45, Sector 35-C, Chandigarh",
        "city": "Chandigarh",
        "distance_km": 1.5,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Holistic joint health, Janu Basti, and classical herbal rasayanas.",
        "slots": ["09:30 AM", "11:30 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 172 260 4567"
    },
    # Homeopathy
    {
        "id": "doc-chd-hom-1",
        "name": "Dr. Simranjeet Kaur",
        "system": "Homeopathy",
        "specialty": "Constitutional Homeopathy & Child Health",
        "degrees": "BHMS, MD (Hom)",
        "experience_years": 14,
        "rating": 4.8,
        "review_count": 270,
        "clinic_name": "Sanitas Homeo Care",
        "address": "SCO 88, Sector 17-D, Chandigarh",
        "city": "Chandigarh",
        "distance_km": 2.1,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Specialized in respiratory and seasonal allergies, sinus decongestion without drowsiness.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 172 270 1234"
    },
    # Allopathy
    {
        "id": "doc-chd-all-1",
        "name": "Dr. Rohit Aggarwal",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD (Med), DM (Gastro, PGIMER Chandigarh)",
        "experience_years": 21,
        "rating": 5.0,
        "review_count": 620,
        "clinic_name": "Max Super Speciality Hospital Mohali",
        "address": "Sector 56A, Near Chandigarh Border, Chandigarh",
        "city": "Chandigarh",
        "distance_km": 2.8,
        "consultation_fee": 1100,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "PGIMER alumnus with extensive diagnostic experience in severe GI disorders and peptic disease.",
        "slots": ["09:00 AM", "11:00 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 172 521 2000"
    },

    # =========================================================================
    #                                BIHAR
    # =========================================================================

    # ------------------ PATNA ------------------
    # Ayurveda
    {
        "id": "doc-pat-ayu-1",
        "name": "Dr. Alok Kumar Rai",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Kayachikitsa & Agni Disorders",
        "degrees": "BAMS, MD (Ayu, Govt Ayurvedic College Patna)",
        "experience_years": 19,
        "rating": 4.9,
        "review_count": 380,
        "clinic_name": "Pataliputra Ayurvedic Chikitsalaya",
        "address": "Kadam Kuan, Near Sahitya Sammelan, Patna",
        "city": "Patna",
        "distance_km": 1.5,
        "consultation_fee": 500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Renowned across Bihar for chronic hyperacidity, liver sluggishness, and classical pulse diagnosis (Nadi Pariksha).",
        "slots": ["09:30 AM", "11:00 AM", "03:00 PM", "05:30 PM", "07:00 PM"],
        "phone": "+91 612 268 4501"
    },
    {
        "id": "doc-pat-ayu-2",
        "name": "Dr. Anjali Pandey",
        "system": "Ayurveda",
        "specialty": "Panchakarma & Joint Spine Care",
        "degrees": "BAMS, MS (Shalya Tantra)",
        "experience_years": 14,
        "rating": 4.8,
        "review_count": 240,
        "clinic_name": "AyuShree Panchakarma Wellness",
        "address": "Boring Road, Opposite Chhabra Complex, Patna",
        "city": "Patna",
        "distance_km": 2.2,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Expert in Sandhigata Vata (osteoarthritis) treatment and herbal Janu Basti oil pool therapies.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 612 255 7890"
    },
    # Homeopathy
    {
        "id": "doc-pat-hom-1",
        "name": "Dr. Manoj K. Srivastava",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Chronic Allergies",
        "degrees": "BHMS, MD (Homeo, Patna Homeopathic Medical College)",
        "experience_years": 22,
        "rating": 4.9,
        "review_count": 490,
        "clinic_name": "Hahnemann Homeo Care Centre",
        "address": "Opposite Pillar No. 45, Bailey Road, Patna",
        "city": "Patna",
        "distance_km": 1.8,
        "consultation_fee": 500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Over 20 years of experience treating recurrent respiratory allergies, migraine, and skin disorders.",
        "slots": ["09:00 AM", "11:30 AM", "02:30 PM", "05:00 PM", "06:30 PM"],
        "phone": "+91 612 223 9911"
    },
    # Allopathy
    {
        "id": "doc-pat-all-1",
        "name": "Dr. Anand Mohan Prasad",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Hepatology",
        "degrees": "MBBS, MD (Med), DM (Gastroenterology, AIIMS)",
        "experience_years": 18,
        "rating": 4.9,
        "review_count": 560,
        "clinic_name": "Paras HMRI Hospital Gastro Suite",
        "address": "NH-30, Bailey Road, Raja Bazar, Patna",
        "city": "Patna",
        "distance_km": 2.5,
        "consultation_fee": 900,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Senior gastroenterologist specializing in therapeutic endoscopy, GERD, and peptic ulcer treatments.",
        "slots": ["09:30 AM", "11:00 AM", "01:30 PM", "04:00 PM"],
        "phone": "+91 612 710 7777"
    },
    {
        "id": "doc-pat-all-2",
        "name": "Dr. Ritu Shekhar",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Metabolic Health",
        "degrees": "MBBS, MD (Medicine, PMCH Patna)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 340,
        "clinic_name": "Medanta Super Speciality Hospital Patna",
        "address": "Kankarbagh Main Road, Patna",
        "city": "Patna",
        "distance_km": 3.1,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Expert clinical evaluations for complex multi-system disorders, fever of unknown origin, and chronic migraines.",
        "slots": ["10:00 AM", "12:00 PM", "03:00 PM", "05:00 PM"],
        "phone": "+91 612 350 5050"
    },

    # ------------------ GAYA ------------------
    # Ayurveda
    {
        "id": "doc-gay-ayu-1",
        "name": "Dr. Satyendra Narayan Singh",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Medicine & Spine Care",
        "degrees": "BAMS (Bihar University), D.A.M.",
        "experience_years": 21,
        "rating": 4.8,
        "review_count": 210,
        "clinic_name": "Bodh Gaya AyurVeda Health Centre",
        "address": "Near Gandhi Maidan, Civil Lines, Gaya",
        "city": "Gaya",
        "distance_km": 1.4,
        "consultation_fee": 400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Holistic Vata pacifying protocols and classical herbal remedies for cervical and lower back distress.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 631 222 1045"
    },
    # Homeopathy
    {
        "id": "doc-gay-hom-1",
        "name": "Dr. Rashmi Sinha",
        "system": "Homeopathy",
        "specialty": "Respiratory & Constitutional Care",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 15,
        "rating": 4.8,
        "review_count": 185,
        "clinic_name": "Sinha Homeo Clinic",
        "address": "Rai Kashinath More, Gaya",
        "city": "Gaya",
        "distance_km": 1.7,
        "consultation_fee": 400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Gentle microdose remedies for seasonal asthma, nasal polyps, and recurrent migraines.",
        "slots": ["10:00 AM", "12:00 PM", "04:00 PM", "06:30 PM"],
        "phone": "+91 631 242 3344"
    },
    # Allopathy
    {
        "id": "doc-gay-all-1",
        "name": "Dr. Rakesh Kumar",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Critical Care",
        "degrees": "MBBS, MD (Medicine, ANMMCH Gaya)",
        "experience_years": 17,
        "rating": 4.9,
        "review_count": 310,
        "clinic_name": "Magadh Medicare Clinic",
        "address": "Medical College Road, Gaya",
        "city": "Gaya",
        "distance_km": 2.4,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Comprehensive clinical management of gastrointestinal disorders, hypertension, and infectious diseases.",
        "slots": ["09:30 AM", "11:30 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 631 241 5566"
    },

    # ------------------ MUZAFFARPUR ------------------
    # Ayurveda
    {
        "id": "doc-muz-ayu-1",
        "name": "Dr. Birendra Thakur",
        "system": "Ayurveda",
        "specialty": "Liver & Metabolic Health",
        "degrees": "BAMS, MD (Ayurveda)",
        "experience_years": 18,
        "rating": 4.8,
        "review_count": 230,
        "clinic_name": "Vaishali Ayurvedic Sansthan",
        "address": "Mithanpura Main Road, Muzaffarpur",
        "city": "Muzaffarpur",
        "distance_km": 1.6,
        "consultation_fee": 450,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Specialized in Pitta detoxification, fatty liver management, and digestive herbal rasayanas.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 621 224 5500"
    },
    # Homeopathy
    {
        "id": "doc-muz-hom-1",
        "name": "Dr. Santosh K. Jha",
        "system": "Homeopathy",
        "specialty": "Pediatric & Skin Homeopathy",
        "degrees": "BHMS, MD (Hom)",
        "experience_years": 16,
        "rating": 4.9,
        "review_count": 290,
        "clinic_name": "Jha Classical Homeo Clinic",
        "address": "Club Road, Near Head Post Office, Muzaffarpur",
        "city": "Muzaffarpur",
        "distance_km": 1.2,
        "consultation_fee": 400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Excellent outcomes in treating childhood recurring coughs, atopic dermatitis, and urticaria.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 621 226 7890"
    },
    # Allopathy
    {
        "id": "doc-muz-all-1",
        "name": "Dr. S. K. Verma",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Internal Medicine",
        "degrees": "MBBS, MD (Medicine, SKMCH Muzaffarpur)",
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 410,
        "clinic_name": "Verma Medical Specialist Center",
        "address": "Juranchapra Main Road, Muzaffarpur",
        "city": "Muzaffarpur",
        "distance_km": 1.9,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Renowned internist for gastrointestinal reflux disease, peptic disorders, and diagnostic ultrasound.",
        "slots": ["09:30 AM", "11:30 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 621 221 4455"
    },

    # ------------------ BHAGALPUR ------------------
    # Ayurveda
    {
        "id": "doc-bhg-ayu-1",
        "name": "Dr. Prabhat Kumar Jha",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Kayachikitsa & Joint Pain",
        "degrees": "BAMS, MD (Ayu)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 190,
        "clinic_name": "Anga Ayurvedic Chikitsa Kendra",
        "address": "Tilkamanjhi Chowk, Bhagalpur",
        "city": "Bhagalpur",
        "distance_km": 1.5,
        "consultation_fee": 400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Natural herbs and Kati Basti for chronic sciatica, spine degeneration, and gut imbalances.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 641 240 1234"
    },
    # Homeopathy
    {
        "id": "doc-bhg-hom-1",
        "name": "Dr. Rita Kumari",
        "system": "Homeopathy",
        "specialty": "Constitutional Care & Chronic Migraine",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 13,
        "rating": 4.8,
        "review_count": 160,
        "clinic_name": "Sanjeevani Homeopathic Care",
        "address": "Zero Mile, Bhagalpur",
        "city": "Bhagalpur",
        "distance_km": 2.1,
        "consultation_fee": 350,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 93,
        "match_reason": "Gentle constitutional remedies for headache syndromes and allergic sneezing.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "05:30 PM"],
        "phone": "+91 641 242 5678"
    },
    # Allopathy
    {
        "id": "doc-bhg-all-1",
        "name": "Dr. Amitabh Sen",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD (Medicine, JLNMCH Bhagalpur)",
        "experience_years": 21,
        "rating": 4.9,
        "review_count": 380,
        "clinic_name": "Sen Medical Care & Research Center",
        "address": "Near Mayaganj Hospital, Bhagalpur",
        "city": "Bhagalpur",
        "distance_km": 1.8,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Leading physician in Eastern Bihar for accurate diagnostic labs, GERD, and metabolic syndromes.",
        "slots": ["09:30 AM", "11:30 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 641 240 8899"
    },

    # ------------------ DARBHANGA ------------------
    # Ayurveda
    {
        "id": "doc-dbg-ayu-1",
        "name": "Dr. Harish Chandra Mishra",
        "system": "Ayurveda",
        "specialty": "Classical Mithila Ayurveda & Agni Treatment",
        "degrees": "BAMS, MD (Ayu)",
        "experience_years": 24,
        "rating": 4.9,
        "review_count": 310,
        "clinic_name": "Mithilanchal Ayurvedic Shodh Sansthan",
        "address": "Near Tower Chowk, Laheriasarai, Darbhanga",
        "city": "Darbhanga",
        "distance_km": 1.3,
        "consultation_fee": 400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Deep tradition of Ayurvedic rasayanas for gastrointestinal Agni balancing and joint flexibility.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 6272 222 345"
    },
    # Homeopathy
    {
        "id": "doc-dbg-hom-1",
        "name": "Dr. Pankaj Kumar Choudhary",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Skin Treatment",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 220,
        "clinic_name": "Choudhary Homeo Health Clinic",
        "address": "Darbhanga Tower Market, Darbhanga",
        "city": "Darbhanga",
        "distance_km": 1.7,
        "consultation_fee": 350,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Individualized totality prescriptions for chronic eczema, boils, and psychosomatic headaches.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 6272 233 456"
    },
    # Allopathy
    {
        "id": "doc-dbg-all-1",
        "name": "Dr. Rajiv Ranjan",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Cardiology",
        "degrees": "MBBS, MD (Medicine, DMCH Darbhanga)",
        "experience_years": 19,
        "rating": 4.9,
        "review_count": 420,
        "clinic_name": "Darbhanga Medical Heart & Gastro Center",
        "address": "Near DMCH Gate No. 2, Darbhanga",
        "city": "Darbhanga",
        "distance_km": 2.1,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "DMCH senior physician specializing in evidence-based acute care, peptic illness, and diagnostics.",
        "slots": ["09:30 AM", "11:30 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 6272 255 678"
    },

    # =========================================================================
    #                           UTTAR PRADESH (UP)
    # =========================================================================

    # ------------------ LUCKNOW ------------------
    # Ayurveda
    {
        "id": "doc-lko-ayu-1",
        "name": "Vaidya Rameshwar Dayal Tripathi",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Kayachikitsa & Panchakarma",
        "degrees": "BAMS, MD (Ayu, State Ayurvedic College Lucknow)",
        "experience_years": 23,
        "rating": 4.9,
        "review_count": 520,
        "clinic_name": "Turiya Wellness Ayurvedic Centre",
        "address": "Vibhuti Khand, Gomti Nagar, Lucknow",
        "city": "Lucknow",
        "distance_km": 1.8,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Premier Vaidya in Lucknow for digestive fire (Agni) restoration, chronic gut acidity, and Nadi Pariksha.",
        "slots": ["09:30 AM", "11:00 AM", "03:00 PM", "05:00 PM", "06:30 PM"],
        "phone": "+91 522 400 1122"
    },
    # Homeopathy
    {
        "id": "doc-lko-hom-1",
        "name": "Dr. Vandana Asthana",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Mind-Body Health",
        "degrees": "BHMS, MD (Homeopathy, National Homeopathic Medical College)",
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 460,
        "clinic_name": "Asthana Classical Homeo Clinic",
        "address": "Hazratganj Main Market, Lucknow",
        "city": "Lucknow",
        "distance_km": 2.3,
        "consultation_fee": 650,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "High reputation in Lucknow for constitutional single-remedy cures for migraine, asthma, and anxiety.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 522 223 4455"
    },
    # Allopathy
    {
        "id": "doc-lko-all-1",
        "name": "Dr. Pradeep Tandon",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Hepatology",
        "degrees": "MBBS, MD, DM (Gastroenterology, SGPGI Lucknow)",
        "experience_years": 24,
        "rating": 5.0,
        "review_count": 710,
        "clinic_name": "Medanta Hospital Lucknow Gastro Suite",
        "address": "Sector A, Pocket 1, Amar Shaheed Path, Golf City, Lucknow",
        "city": "Lucknow",
        "distance_km": 3.2,
        "consultation_fee": 1200,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "SGPGI alumnus with national acclaim in treating acid reflux, GI motility, and endoscopic interventions.",
        "slots": ["09:00 AM", "10:30 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 522 450 5050"
    },

    # ------------------ VARANASI ------------------
    # Ayurveda
    {
        "id": "doc-vns-ayu-1",
        "name": "Acharya Dr. Devendra Nath Dwivedi",
        "system": "Ayurveda",
        "specialty": "Classical Nadi Pariksha & Kayachikitsa",
        "degrees": "BAMS, MD, Ph.D (Ayurveda, IMS-BHU Varanasi)",
        "experience_years": 27,
        "rating": 5.0,
        "review_count": 820,
        "clinic_name": "Kashi Vishwanath Ayurvedic Research Foundation",
        "address": "Lanka Road, Near BHU Main Gate, Varanasi",
        "city": "Varanasi",
        "distance_km": 1.2,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Senior Ayurvedic scholar from BHU with global acclaim for classical dosha harmonization and rasayana healing.",
        "slots": ["08:30 AM", "10:30 AM", "03:00 PM", "05:30 PM", "07:00 PM"],
        "phone": "+91 542 236 8899"
    },
    # Homeopathy
    {
        "id": "doc-vns-hom-1",
        "name": "Dr. Shailendra K. Upadhyay",
        "system": "Homeopathy",
        "specialty": "Constitutional Homeopathy & Allergy Care",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 18,
        "rating": 4.8,
        "review_count": 310,
        "clinic_name": "Ganga Homeo Healing Studio",
        "address": "Ravindrapuri Road, Near Assi Ghat, Varanasi",
        "city": "Varanasi",
        "distance_km": 1.9,
        "consultation_fee": 500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Holistic treatments for severe migraine headaches, skin urticaria, and gastrointestinal acidity.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 542 231 4567"
    },
    # Allopathy
    {
        "id": "doc-vns-all-1",
        "name": "Dr. Anurag Tandon",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Hepatology",
        "degrees": "MBBS, MD, DM (Gastroenterology, IMS-BHU)",
        "experience_years": 21,
        "rating": 4.9,
        "review_count": 590,
        "clinic_name": "Apex Super Speciality Hospital",
        "address": "DLW Hydel Road, Varanasi",
        "city": "Varanasi",
        "distance_km": 2.6,
        "consultation_fee": 900,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "High precision clinical endoscopy and modern targeted pharmacotherapy for peptic diseases.",
        "slots": ["09:00 AM", "11:00 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 542 231 9900"
    },

    # ------------------ KANPUR ------------------
    # Ayurveda
    {
        "id": "doc-knp-ayu-1",
        "name": "Dr. Om Prakash Shukla",
        "system": "Ayurveda",
        "specialty": "Joint Disorders & Vata Shaman",
        "degrees": "BAMS, MD (Ayurveda)",
        "experience_years": 22,
        "rating": 4.9,
        "review_count": 390,
        "clinic_name": "Kanpur AyurVaid Clinic",
        "address": "Swaroop Nagar, Near Arya Nagar, Kanpur",
        "city": "Kanpur",
        "distance_km": 1.7,
        "consultation_fee": 600,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Classical herbal oils and Panchakarma for chronic spondylosis and degenerative arthritis.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 512 255 1234"
    },
    # Homeopathy
    {
        "id": "doc-knp-hom-1",
        "name": "Dr. Akhilesh Nigam",
        "system": "Homeopathy",
        "specialty": "Allergy, Asthma & Skin Relief",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 17,
        "rating": 4.8,
        "review_count": 280,
        "clinic_name": "Nigam Homeo PolyClinic",
        "address": "Civil Lines, Near Green Park, Kanpur",
        "city": "Kanpur",
        "distance_km": 2.1,
        "consultation_fee": 500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Trusted clinical results in allergic bronchitis, persistent sneezing, and urticaria.",
        "slots": ["10:00 AM", "12:00 PM", "04:00 PM", "06:30 PM"],
        "phone": "+91 512 230 4567"
    },
    # Allopathy
    {
        "id": "doc-knp-all-1",
        "name": "Dr. R. K. Bansal",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Internal Medicine",
        "degrees": "MBBS, MD, DM (Gastroenterology, GSVM Medical College)",
        "experience_years": 23,
        "rating": 4.9,
        "review_count": 580,
        "clinic_name": "Regency Hospital Gastroenterology Centre",
        "address": "A-2, Sarvodaya Nagar, Kanpur",
        "city": "Kanpur",
        "distance_km": 2.5,
        "consultation_fee": 1000,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "Renowned gastroenterologist in Kanpur for upper endoscopy, GERD, and peptic ulcer therapy.",
        "slots": ["09:30 AM", "11:30 AM", "02:00 PM", "04:30 PM"],
        "phone": "+91 512 308 1111"
    },

    # ------------------ PRAYAGRAJ ------------------
    # Ayurveda
    {
        "id": "doc-pry-ayu-1",
        "name": "Vaidya Shyam Sunder Tiwari",
        "system": "Ayurveda",
        "specialty": "Panchakarma & Agni Restoration",
        "degrees": "BAMS, MD (Ayu)",
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 340,
        "clinic_name": "Triveni Ayurvedic Health Sansthan",
        "address": "George Town, Near Tagore Town, Prayagraj",
        "city": "Prayagraj",
        "distance_km": 1.6,
        "consultation_fee": 500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Classical Ayurvedic herbal formulations for stomach burning, indigestion, and vitality (Ojas).",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 532 246 1234"
    },
    # Homeopathy
    {
        "id": "doc-pry-hom-1",
        "name": "Dr. Amitava Mukherjee",
        "system": "Homeopathy",
        "specialty": "Constitutional Homeopathy & Migraines",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 270,
        "clinic_name": "Mukherjee Homeo Clinic",
        "address": "Civil Lines, Sardar Patel Marg, Prayagraj",
        "city": "Prayagraj",
        "distance_km": 1.8,
        "consultation_fee": 450,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Gentle non-steroidal micro-potencies for neurological headaches and skin rashes.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 532 226 5678"
    },
    # Allopathy
    {
        "id": "doc-pry-all-1",
        "name": "Dr. Sanjay Gupta",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD (Medicine, MLN Medical College Prayagraj)",
        "experience_years": 22,
        "rating": 4.9,
        "review_count": 470,
        "clinic_name": "Sangam Medicare Hospital",
        "address": "Ashok Nagar, Near High Court, Prayagraj",
        "city": "Prayagraj",
        "distance_km": 2.2,
        "consultation_fee": 800,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Expert evidence-based medical diagnostics for acute acid peptic disease and chronic fever.",
        "slots": ["09:30 AM", "11:30 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 532 242 7890"
    },

    # ------------------ AGRA ------------------
    # Ayurveda
    {
        "id": "doc-agr-ayu-1",
        "name": "Dr. Jitendra Pal Singh",
        "system": "Ayurveda",
        "specialty": "Skin Diseases & Ayurvedic Detox (Twak Roga)",
        "degrees": "BAMS, MD (Ayu)",
        "experience_years": 17,
        "rating": 4.8,
        "review_count": 260,
        "clinic_name": "Taj AyurVeda Healing Center",
        "address": "Sanjay Place, Commercial Complex, Agra",
        "city": "Agra",
        "distance_km": 1.5,
        "consultation_fee": 500,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "Herbal blood purifiers and Lepam therapies for chronic eczema, psoriasis, and acidity.",
        "slots": ["09:30 AM", "11:30 AM", "03:00 PM", "05:00 PM"],
        "phone": "+91 562 285 1122"
    },
    # Homeopathy
    {
        "id": "doc-agr-hom-1",
        "name": "Dr. Sunita Sharma",
        "system": "Homeopathy",
        "specialty": "Constitutional Care & Chronic Allergies",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 14,
        "rating": 4.8,
        "review_count": 210,
        "clinic_name": "Sharma Homeo Clinic",
        "address": "Fatehabad Road, Near Tourist Complex, Agra",
        "city": "Agra",
        "distance_km": 2.0,
        "consultation_fee": 450,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=300&auto=format&fit=crop&q=80",
        "match_score": 93,
        "match_reason": "Specialized in non-drowsy remedies for dust allergies, allergic rhinitis, and migraines.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 562 233 4455"
    },
    # Allopathy
    {
        "id": "doc-agr-all-1",
        "name": "Dr. Nitin Agarwal",
        "system": "Allopathy",
        "specialty": "Internal Medicine & Gastroenterology",
        "degrees": "MBBS, MD (Medicine, SN Medical College Agra)",
        "experience_years": 19,
        "rating": 4.9,
        "review_count": 430,
        "clinic_name": "Pushpanjali Hospital & Research Centre",
        "address": "Delhi Gate, Agra",
        "city": "Agra",
        "distance_km": 2.3,
        "consultation_fee": 800,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "Senior medical specialist with modern gastrointestinal diagnostic workups and ICU care.",
        "slots": ["09:00 AM", "11:00 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 562 226 5000"
    },

    # ------------------ GORAKHPUR ------------------
    # Ayurveda
    {
        "id": "doc-gkp-ayu-1",
        "name": "Dr. Arvind Kumar Pandey",
        "system": "Ayurveda",
        "specialty": "Ayurvedic Kayachikitsa & Panchakarma",
        "degrees": "BAMS, MD (Ayu)",
        "experience_years": 21,
        "rating": 4.9,
        "review_count": 350,
        "clinic_name": "Gorakhnath AyurVaidya Kendra",
        "address": "Golghar Main Market, Gorakhpur",
        "city": "Gorakhpur",
        "distance_km": 1.4,
        "consultation_fee": 450,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=300&auto=format&fit=crop&q=80",
        "match_score": 97,
        "match_reason": "Holistic treatments for hyperacidity, digestive weakness (Agni Mandya), and joint pain.",
        "slots": ["09:00 AM", "11:00 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 551 233 4567"
    },
    # Homeopathy
    {
        "id": "doc-gkp-hom-1",
        "name": "Dr. Vikas Srivastava",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Skin Relief",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 16,
        "rating": 4.8,
        "review_count": 240,
        "clinic_name": "Srivastava Classical Homeo",
        "address": "Betiahata, Near Park Road, Gorakhpur",
        "city": "Gorakhpur",
        "distance_km": 1.8,
        "consultation_fee": 400,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 94,
        "match_reason": "Effective minimum-dose remedies for chronic hives, eczema, and asthma.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 551 220 1234"
    },
    # Allopathy
    {
        "id": "doc-gkp-all-1",
        "name": "Dr. Abhishek Mall",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Internal Medicine",
        "degrees": "MBBS, MD (Med), DM (Gastroenterology, AIIMS Gorakhpur)",
        "experience_years": 15,
        "rating": 4.9,
        "review_count": 390,
        "clinic_name": "AIIMS Gorakhpur Specialty Clinic",
        "address": "Kunaraghat, Medical College Road, Gorakhpur",
        "city": "Gorakhpur",
        "distance_km": 3.0,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 98,
        "match_reason": "AIIMS specialist with state-of-the-art diagnostic endoscopy for acid peptic conditions.",
        "slots": ["09:30 AM", "11:30 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 551 220 5000"
    },

    # ------------------ NOIDA ------------------
    # Ayurveda
    {
        "id": "doc-noi-ayu-1",
        "name": "Dr. Deepa Aggarwal",
        "system": "Ayurveda",
        "specialty": "Stress, Digestion & Lifestyle Disorders",
        "degrees": "BAMS, MD (Kayachikitsa)",
        "experience_years": 16,
        "rating": 4.9,
        "review_count": 320,
        "clinic_name": "Prakriti AyurVeda Healing Studio",
        "address": "Sector 62, Near Electronic City Metro, Noida",
        "city": "Noida",
        "distance_km": 1.6,
        "consultation_fee": 750,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1594824813589-323bc01b44b8?w=300&auto=format&fit=crop&q=80",
        "match_score": 96,
        "match_reason": "Specialized in corporate stress, GERD, insomnia, and Shirodhara calming therapies.",
        "slots": ["09:30 AM", "11:30 AM", "03:00 PM", "05:30 PM"],
        "phone": "+91 120 456 7890"
    },
    # Homeopathy
    {
        "id": "doc-noi-hom-1",
        "name": "Dr. Saurabh Gupta",
        "system": "Homeopathy",
        "specialty": "Classical Homeopathy & Allergy Relief",
        "degrees": "BHMS, MD (Homeo)",
        "experience_years": 15,
        "rating": 4.8,
        "review_count": 290,
        "clinic_name": "CuraLife Homeopathy Clinic",
        "address": "Sector 18, Near Atta Market, Noida",
        "city": "Noida",
        "distance_km": 2.1,
        "consultation_fee": 700,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=300&auto=format&fit=crop&q=80",
        "match_score": 95,
        "match_reason": "High success in air pollution allergies, sinus polyps, and recurrent migraines.",
        "slots": ["10:00 AM", "12:00 PM", "03:30 PM", "06:00 PM"],
        "phone": "+91 120 251 1234"
    },
    # Allopathy
    {
        "id": "doc-noi-all-1",
        "name": "Dr. Rajesh Kumar",
        "system": "Allopathy",
        "specialty": "Gastroenterology & Hepatology",
        "degrees": "MBBS, MD, DM (Gastroenterology, AIIMS Delhi)",
        "experience_years": 20,
        "rating": 4.9,
        "review_count": 610,
        "clinic_name": "Fortis Hospital Noida Gastro Center",
        "address": "B-22, Sector 62, Noida",
        "city": "Noida",
        "distance_km": 2.4,
        "consultation_fee": 1100,
        "available_today": True,
        "available_modes": ["In-Clinic", "Video Consultation"],
        "image_url": "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=300&auto=format&fit=crop&q=80",
        "match_score": 99,
        "match_reason": "AIIMS trained gastroenterologist with advanced endoscopic diagnostic and GERD treatment suites.",
        "slots": ["09:00 AM", "11:00 AM", "01:30 PM", "04:30 PM"],
        "phone": "+91 120 430 0222"
    },
]
